### ISSUE TITLE
MemoryError running stft

### ISSUE THREAD

**Issue by endolith** [bmcfee/librosa#149]
I was going to write an `stft`/`istft` function for SciPy, found this library already has one, and tried it out.  First example from http://nbviewer.ipython.org/github/bmcfee/librosa/blob/master/examples/LibROSA%20demo.ipynb resulted in MemoryError on my machine.  So it looks like you are doing what I was going to do, breaking it up into chunks and doing N-D FFTs on each one for speed?  But I couldn't find any guide on how to tell how much memory to use for each chunk.

This is kind of ugly, but it works for me:

    global _MAX_MEM_BLOCK
    while True:
        try:
            # how many columns can we fit within MAX_MEM_BLOCK?
            n_columns = int(_MAX_MEM_BLOCK / (stft_matrix.shape[0]
                                              * stft_matrix.itemsize))

            for bl_s in range(0, stft_matrix.shape[1], n_columns):
                bl_t = min(bl_s + n_columns, stft_matrix.shape[1])

                # RFFT and Conjugate here to match phase from DPWE code
                stft_matrix[:, bl_s:bl_t] = fft.rfft(fft_window
                                                     * y_frames[:, bl_s:bl_t],
                                                     axis=0).conj()
            break
        except MemoryError:
            _MAX_MEM_BLOCK /= 2

**Comment by bmcfee** [comment]
> But I couldn't find any guide on how to tell how much memory to use for each chunk.

True, this parameter isn't currently exposed to the user.  The default block size was chosen somewhat arbitrarily, with the idea in mind that a savvy user might tweak it directly.

FWIW, 0.4 will include some parameters that are set in the environment (and I suppose, an ini file), and it would be simple to add a hook for the memory block size.

Still, it's strange that the demo notebook was bombing out of memory for you.  How small did your dynamic block size have to go before it worked?

**Comment by ebattenberg** [comment]
It would be good to have the parameter exposed as a kwarg, as the optimal blocksize will probably vary with all the other params (and the target cpu architecture).  In my experience with tuning things like this, the optimal block-size is more influenced by cache size than it is main memory size, so my blocksizes end up being quite a bit smaller than 128MB (on the order of ~8MB depending on the CPU).

**Comment by endolith** [comment]
> True, this parameter isn't currently exposed to the user. 

I meant I couldn't find any guide on how to know how much memory is ok for Python to try to use.  But documenting this variable somewhere would be good, too.

> Still, it's strange that the demo notebook was bombing out of memory for you. How small did your dynamic block size have to go before it worked?

Well I was running it on a PC with memory-heavy web browser etc running in the background.  It works reliably with 32 MiB.  Sometimes it works with 64 MiB, other times "It seems the kernel died unexpectedly" and the try/except doesn't catch it.

**Comment by bmcfee** [comment]
> In my experience with tuning things like this, the optimal block-size is more influenced by cache size than it is main memory size, so my blocksizes end up being quite a bit smaller than 128MB (on the order of ~8MB depending on the CPU).

Indeed!

I hacked up a quick notebook to benchmark this in the dev branch, and the results are [here](http://nbviewer.ipython.org/gist/bmcfee/a53223288773538826e8).

nb: this benchmark was computed on a lenovo x1 carbon (Intel Core i7 i7-4600U 2.10 GHz, 8GB ram), so your mileage may vary.

For sure worth exposing and documenting this feature though.  I'm not 100% convinced that a parameter is the best way to do this, since it:

1. doesn't affect the output (only speed/efficiency)
2. pops up in a few different functions (istft, ifgram, etc)
3. to be effective, the parameter would have to be threaded through all the functions that wrap stft (& friends), which is pretty much everything.

I think an environment/settable variable in the spirit of `np.set_printoptions` would be a bit more natural, but I'm open to convincing arguments to the contrary.

At any rate, thanks @endolith and @ebattenberg for bringing this to my attention!

**Comment by endolith** [comment]
Well ideally it would just use as much memory as possible, trying to allocate different sizes until it succeeds, but it doesn't seem Python provides any reliable way to do this?

**Comment by bmcfee** [comment]
> Well ideally it would just use as much memory as possible, trying to allocate different sizes until it succeeds, but it doesn't seem Python provides any reliable way to do this?

Maybe, but like @ebattenberg suggests, using bigger batch blocks doesn't necessarily translate to faster computation, which is really the only reason to use blocks rather than column-wise iteration in the first place.  Seems like aside from python's memory abstraction, virtual memory in general would make this sort of thing nasty to compute in practice anyway.

**Comment by ebattenberg** [comment]
@bmcfee The results in that notebook are interesting.  It seems like the fastest blocksize is around the L2 cache size.  One caveat when timing things in loops: the effects of cache warming can influence your relative timings.

**Comment by bmcfee** [comment]
So, aside from reducing the block size, I don't see any need to do any major rewriting of stft right now.  All of the demo code and default parameters have been updated to use a 23ms hop, so you shouldn't hit any snags out of the box.

The 0.5 milestone issue #157 includes porting core components to cython, and specifically I'll be targeting `stft` (and friends), and a few other tight-loop functions that would make sense to accelerate.  At that point, I think the chunking parameter will become moot (due to operating in-place on preallocated memory), and the rest of this issue will resolve itself.

Anyone object to me marking as `wontfix` and closing this issue?

**Comment by endolith** [comment]
I'd say changing the block size counts as a fix
