### ISSUE TITLE
User-settable/gettable global default parameters

### ISSUE THREAD

**Issue by craffel** [bmcfee/librosa#204]
Sorry  if this is addressed in another issue, I wasn't able to find reference to it although I remember it being discussed.  Now that most of the parameters are pretty standardized (`sr=22050`, `n_fft=2048`, `hop=n_fft/4`, etc), it would be cool if it was easy to retrieve these global default parameter values, or better, to set them by hand.  This would make user code potentially less verbose, but is not at all necessary.  It also could make user code slightly less error-prone, for example in the case where the user is using a sampling rate which is not 22050 - if they don't remember to update `n_fft` in every function call they make which does spectral processing, they'll have a bad time.  Is this something planned?  The main drawback that I see is that it could potentially make the documentation uglier.

**Comment by bmcfee** [comment]
I like the idea, and it's something that's been in the back of my head for a while.

Do you know of any good way to do this, consistently, without wrecking the docstrings or call signatures?

**Comment by craffel** [comment]
> Do you know of any good way to do this, consistently, without wrecking the docstrings or call signatures?

No, I don't.  The only thing I could think of is some kind of hack where you have a decorator which replaces keyword arguments with the config values based on their name... something like
```Python
defaults = {'sr': 22050}
def replace_defaults(foo):
    def replaced(*args, **kwargs):
        if 'sr' in kwargs:
            kwargs['sr'] = defaults['sr']
        return foo(*args, **kwargs)
    return replaced
```
Then you could still define a function with the normal defaults and it would show up as normal in docs/function code/etc., but they would be replaced by the global defaults.  Not proposing this as a good solution, but it's what I can think of OTOH.  Googling doesn't bring anything up.  The only other library I regularly use which has global defaults is Theano, but I don't think they're using them to set any keyword argument defaults.

**Comment by bmcfee** [comment]
The decorator hack seems like the only viable approach here, but I doubt it can ever be made safe or dynamically consistent.

We might be able to use functools to mangle the docstrings/call signature when the function is first defined, kind of like how the `cache` object currently works.  I can see two downsides though:

* The defaults object would have to be constructed before all function definitions are executed.  This is possible, but tricky, and probably requires either environment variables or config files to pull off in a usable way.  Not that I'm against either of those things.

* The `defaults` dict would have to be frozen.  Otherwise, if it changes after the decorator executes, the  default variables (and, probably, mangled docstrings) are no longer consistent.

My general sneaking suspicion here is that, yes, this whole endeavor may be possible, but it might take a lot of work to get right, and complicate the code quite a bit.  I'm not sure there's enough demand  for this feature to justify going down this route.

**Comment by craffel** [comment]
Well, I wasn't necessarily seeing the call signatures and docstrings being always correct/consistent as being a requirement, especially if there is note somewhere saying that once global config values are set, the docstrings/call signatures may be inconsistent.  If the user were to set a global parameter, they probably would expect that.  I'm not advocating for this, of course...  Otherwise, yes, we'd need to use environment variables or a config file and then mangle the call signatures/docstring at import-time, which would take a lot of legwork.

**Comment by bmcfee** [comment]
> Well, I wasn't necessarily seeing the call signatures and docstrings being always correct/consistent as being a requirement, especially if there is note somewhere saying that once global config values are set, the docstrings/call signatures may be inconsistent.

That seems like asking for trouble, especially when it comes to users of ipython/jupyter/other IDEs that dynamically render this stuff.  I know that I would find it really confusing.

Going back to the original post: is there a particular use case that you have in mind?  I'm all in favor of reducing careless user errors, but I'm having a hard time coming up with other cases.

An idea for a compromise: rather than bolting on a bunch of complicated logic to set/get defaults, we could probably come up with a decorator that warns if a user changes one default parameter but not other (dependent) parameters.  I'm not sure if this is too [clippyesque](https://en.wikipedia.org/wiki/Office_Assistant), but it would be relatively simple and reduce errors, without making the rest of our lives difficult.

**Comment by craffel** [comment]
> That seems like asking for trouble, especially when it comes to users of ipython/jupyter/other IDEs that dynamically render this stuff. I know that I would find it really confusing.

Yeah, I don't think it's a good solution.

> is there a particular use case that you have in mind? I'm all in favor of reducing careless user errors, but I'm having a hard time coming up with other cases.

Sure:
* You have a large corpus of audio files sampled at a sampling rate other than 22050 Hz, and you want to process them all with librosa.  If you update all of the appropriate spectral parameters, you can avoid resampling (or maybe you have things at 44.1 kHz and you care about very high frequencies for some reason).  Doing this without defaults would make the code verbose and bug-prone (in terms of remembering to update all of the parameters for all function calls).

* You're calling everything with the default parameterization (as you probably should), but you're also using another module, and you want to know what parameters are being used for your analysis.

> we could probably come up with a decorator that warns if a user changes one default parameter but not other (dependent) parameters.

I think the main one which matters is the sampling rate, honestly.  If the user prevents resampling in `load`, they might have a bad time later on.  This is vaguely related to the discussion of whether frame/hop sizes should be provided in seconds or samples, which I think we had a long time ago.

At any rate, I don't think this is a requirement at all - definitely more of a convenience.

**Comment by bmcfee** [comment]
> You have a large corpus of audio files sampled at a sampling rate other than 22050 Hz, and you want to process them all with librosa. If you update all of the appropriate spectral parameters, you can avoid resampling (or maybe you have things at 44.1 kHz and you care about very high frequencies for some reason). Doing this without defaults would make the code verbose and bug-prone (in terms of remembering to update all of the parameters for all function calls).

This, I think, is better handled by the application developer providing wrapper functions with the parameters self-contained.


> You're calling everything with the default parameterization (as you probably should), but you're also using another module, and you want to know what parameters are being used for your analysis.

That's certainly doable, since it's a read-only operation.  I see now downside in adding that functionality (as a named tuple or something).



> I think the main one which matters is the sampling rate, honestly. If the user prevents resampling in load, they might have a bad time later on.

Sure, but there's no preventing this in general; there's no telling what users may or may not forget to do.  I think it's generally better (from a readability and maintenance perspective) to keep defaults simple and well-defined, rather than obscured through some kind of registry object.

**Comment by craffel** [comment]
> This, I think, is better handled by the application developer providing wrapper functions with the parameters self-contained.

I'm not sure what you mean.

> That's certainly doable, since it's a read-only operation. I see now downside in adding that functionality (as a named tuple or something).

For sure.  It's currently doable with `inspect.getargspec`, but that's kind of ugly from a user's point of view...

**Comment by bmcfee** [comment]
> I'm not sure what you mean.

I suppose I mean relying on the user to do it right.  Maybe I don't fully understand the use case you described, but it seems like if the user wants custom parameters, it's up to the user to specify them?  I usually do this by writing a single function that produces all analysis of a particular track.  This way, all the parameters are localized at one point of the code.



> For sure. It's currently doable with inspect.getargspec, but that's kind of ugly from a user's point of view...

Not really; not every function touches every default parameter.  (STFT, for instance, doesn't know about `sr`.)  But yeah, a simple structure called `librosa.DEFAULTS` would be the way to go.

**Comment by bmcfee** [comment]
I did some more thinking on this, and I think we shouldn't do it.  (Or, at least, not in the ways described above.)

Aside from all of the technical challenges involved in getting it to work in the first place, I don't like the idea of having implicit state in functions.  (This would be fine in class methods, where it's obvious that  state must be confined to the object.)

Let's imagine a hypothetical example in which you have librosa, a second library `dep` on top of librosa that does some high-level processing (eg, `laplacian_segmentation`), and you want to develop an application using both along with custom default parameters.

The proposed solutions in this thread generally work by invoking decorators, and thus need to be run at import time.  This could have unpredictable consequences because `dep` may make different assumptions about the defaults.  This could potentially be circumvented by using a context manager to sequester modifications -- [seaborn](https://stanford.edu/~mwaskom/software/seaborn/tutorial/aesthetics.html#temporarily-setting-figure-style) does something like this -- but it seems really overwrought, and you'd still have to rely on `dep` to reset the context.

Overall, I can't imagine a way of doing this statically that wouldn't make the average user's life more difficult in the long run.

---

I think the best solution, if you really want this sort of thing, is to provide an object layer on top of librosa that encapsulates all of the default parameters and provides a method interface to the underlying analysis functions.  An example usage of this might look like the following:

```python
>>> L = librosa.librosa(sr=44100, hop_length=1024)
>>> y, sr = L.load(L.example_audio_file())
>>> C = L.cqt(y)
...
```

where the `L` object is dynamically constructed with the given default arguments, and simply clobbers the defaults of the function being dispatched first by its own defaults, and then any args/kwargs supplied by the caller.

This functionality seems absurdly abstract and general though.  Perhaps it would be best implemented as a standalone module?

**Comment by craffel** [comment]
> Overall, I can't imagine a way of doing this statically that wouldn't make the average user's life more difficult in the long run.

Yes, I don't think the solutions discussed in this thread are very good, and I don't think there's a simple way to do this.  But, I still stand by this:

> I think the main one which matters is the sampling rate, honestly. If the user prevents resampling in load, they might have a bad time later on. This is vaguely related to the discussion of whether frame/hop sizes should be provided in seconds or samples, which I think we had a long time ago.

I would almost say that what it fundamentally comes down to is that a np.ndarray of samples is an incomplete description of an audio signal, because you don't know the sampling rate.  I'd almost advocate subclassing np.ndarray and creating a class which simply had a `sr` member denoting the sampling rate.  But, I'm not going to advocate for that.

I also still think a read-only object which contains default parameters (mainly sampling rate, frame size, hop size) would be a useful add-on, especially if these things are pending changes in the future.

> This functionality seems absurdly abstract and general though.

Yes, I think that would be overwrought.

**Comment by bmcfee** [comment]
> I would almost say that what it fundamentally comes down to is that a np.ndarray of samples is an incomplete description of an audio signal, because you don't know the sampling rate. I'd almost advocate subclassing np.ndarray and creating a class which simply had a sr member denoting the sampling rate. But, I'm not going to advocate for that.

Sure.  That would maybe solve one tiny corner of this general problem, but I think it's too specific to be worth doing.  (FWIW, the astropy folks did this kind of thing, and it seems like a pretty massive undertaking.)



> I also still think a read-only object which contains default parameters (mainly sampling rate, frame size, hop size) would be a useful add-on, especially if these things are pending changes in the future.
> 
>> This functionality seems absurdly abstract and general though.
>
> Yes, I think that would be overwrought.

Actually, I've almost got it working.  It's a big pile of hack that crawls a module tree and wraps up each encountered function in a decorator that squashes defaults against the object's dictionary.  I think it won't even need to be read-only, and it should play nicely with cross-submodule references.  I'll gist it at you if/when it does something useful.

**Comment by bmcfee** [comment]
Ok, I think it works.

https://gist.github.com/93f1666b44a0da899ead

**Comment by bmcfee** [comment]
I'm forking this out into a new package [here](https://github.com/bmcfee/presets).  The current revision works, though it needs testing and docs.

I think this functionality is now outside the scope of librosa, so if it's ok by everyone else, I'd like to close out this issue.

**Comment by craffel** [comment]
Yes, that looks awesome and a little scary, but definitely seems to be outside of the scope of `librosa`.

**Comment by bmcfee** [comment]
Ok.

Note to future users: this functionality is subsumed by the [presets](https://github.com/bmcfee/presets) module.
