### ISSUE TITLE
librosa overwrites default colormap

### ISSUE THREAD

**Issue by ebattenberg** [bmcfee/librosa#222]
Importing librosa overwrite's matplotlib's default colormap.  

```python
import matplotlib as mpl

print mpl.rcParams['image.cmap']

import librosa

print mpl.rcParams['image.cmap']
```

Output is:
```bash
jet
Greys
```

I looked into it briefly and couldn't figure out where this is happening.

**Comment by bmcfee** [comment]
This is a side effect of importing seaborn in librosa.display.

```python
In [1]: import matplotlib as mpl

In [2]: mpl.rcParams['image.cmap']
Out[2]: u'jet'

In [3]: import seaborn as sns

In [4]: mpl.rcParams['image.cmap']
Out[4]: u'Greys'
```

I took a quick skim through the seaborn source, and I don't see any way to disable this behavior since it calls `set()` in `__init__.py`.

I agree that this side effect is undesirable, and we have a couple of options to circumvent it:

1. Drop the seaborn dependency.  We're only using it to get cubehelix, which is nice but non-essential.  If we do this, I'd like to refactor the cmap code a bit so that the user can register target colormaps for the different data types.
2. Stack the matplotlb config before and after import seaborn.  This would look something like:
``python
mplrc = copy.deepcopy(mpl.rcParams)
import seaborn as sns
mpl.rcParams = mplrc
```
This would keep librosa working as is, but seaborn side effects will only occur if the user explicitly imports seaborn separately.  This is a crude hack, but it ought to work.
3. Do nothing.  mpl2 will change default settings anyway, so the side effect should disappear on up-to-date installations within a few months.  This is rather inelegant, but easy.

**Comment by ebattenberg** [comment]
I'd vote for 1. but that's because I don't use any of the `display` functionality and I'm in favor of fewer non-essential dependencies.  It may take a long time for the majority of people to benefit from 3.  Number 2 is a worthwhile hack in the meantime if we're not willing to do number 1.

**Comment by bmcfee** [comment]
You totally should use the display functionality though :)

I like option 2, since it keeps all functionality and eliminates unintended side-effects.
