### ISSUE TITLE
unit tests fail for scipy version 0.13.2

### ISSUE THREAD

**Issue by rabitt** [bmcfee/librosa#241]
First failing test:
```python
ERROR: test_constantq.test_cqt(array([ 1.,  0.,  0., ...,  0.,  0.,  0.]), 11025, 512, 3000, 1, 12, 0.0, 2, None, 1, 0.01)
```

**Comment by bmcfee** [comment]
This comes from #146 ; we need to upgrade the scipy minimum version requierment.

**Comment by bmcfee** [comment]
@rabitt could you dig up the exact error message that was reported?  I'd like to be able to specify the correct minimum scipy version to avoid this failure.

**Comment by bmcfee** [comment]
```
test_constantq.test_hybrid_cqt(512, None, 1, 24, None, 2, 2, 0.01) ... FAIL

======================================================================
FAIL: test_constantq.test_hybrid_cqt(512, None, 1, 24, None, 2, 2, 0.01)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/bmcfee/miniconda/envs/test-scipy/lib/python3.3/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/bmcfee/git/librosa/tests/test_constantq.py", line 113, in __test
    assert np.mean(np.abs(C1 - C2)) < 1e-3
AssertionError
```

**Comment by bmcfee** [comment]
[Paging @ebattenberg ]

This problem is not due to the scipy version, but rather derives from using `scipy.resample` inside `hybrid_cqt`.  I think this error derives from the test fixture (an impulse train), and not the implementation itself.

@ebattenberg : is there a reason we used an impulse train here?  Changing https://github.com/bmcfee/librosa/blob/master/tests/test_constantq.py#L87-L89 to a pure sine tone @ 440Hz fixes the problem and the tests pass.  (I suppose it should work either way, but that's maybe beside the point.)

**Comment by ebattenberg** [comment]
Sorry about the delay.  I'm having trouble getting Google Inbox to not throw all my github notification emails away.  The reason to use an impulse train is that it gives a wide band signal so you can see that the amplitudes across different octaves are as expected.  I know that a sine wave isn't exactly sparse in frequency because of the window effects, so if you want to use a sine that's fine.  It's concerning that the resampling doesn't work with a pulse train.  Why is that?  Just a far different anti-aliasing filter?

**Comment by bmcfee** [comment]
> The reason to use an impulse train is that it gives a wide band signal so you can see that the amplitudes across different octaves are as expected.

Sure, that makes sense.  Thanks for the clarification.


> I know that a sine wave isn't exactly sparse in frequency because of the window effects, so if you want to use a sine that's fine.

I did a bit more experimentation with this in a local branch, and it seems to cause some unexpected failures.  I may dig into this more later, but your response above is compelling enough to drop this approach anyway.


> It's concerning that the resampling doesn't work with a pulse train. Why is that? Just a far different anti-aliasing filter?

I suppose so.  I chalk it up to weirdness inside scipy's resampler. Or, perhaps scipy is doing it right and libsamplerate is doing bad things that result in the test signals being sufficiently close anyway?  Tough to say without really digging into the guts of the resamplers.

**Comment by bmcfee** [comment]
[This notebook](https://gist.github.com/bmcfee/3e20e84868c4b4ad4321) should maybe clarify some things here.

It generates the same kind of impulse train used in the current cqt tests, computes full and hybrid cqt with and without libsamplerate, and shows the results of a single step of downsampling with and without libsamplerate.

The obvious difference is the ringing induced by `sinc_best`, which is absent in the scipy resampler.

The full cqts agree with each other down to about 1e-4 with and without libsamplerate (and likewise for hybrid), though full and hybrid do not agree so closely (tolerance is about 2e-3).

**Comment by bmcfee** [comment]
Quick follow-up: setting `norm=0.5` gets our max deviation down into the 1e-6 range.  Any thoughts on what's going on there?

**Comment by bmcfee** [comment]
I updated the notebook to use a [sine sweep](https://gist.github.com/bmcfee/e7b864cc1b8301b1d9a3) instead of an impulse train, and the plot thickens.  The errors seem to alternate in severity every other octave in the downsampling regime.  Importantly, the ringing artifacts are not present in the downsampled signal here, so I don't think it's (necessarily) to blame for the stft-vs-cqt discrepancy.
