### ISSUE TITLE
Setup script exited with error: Microsoft Visual C++ 10.0 is required

### ISSUE THREAD

**Issue by lwaldner** [bmcfee/librosa#262]
Can you please fix the error "Setup script exited with error: Microsoft Visual C++ 10.0 is required". You can't install the old c++ compiler because a newer one is already installed and their are existing hacks that allow you to install it but it would be nice if the native installation would work.

**Comment by bmcfee** [comment]
I don't understand this issue.  Can you post a log of what exactly happened when you tried to install?

I've never tried to install librosa on a windows environment, though I have heard of people making it work (see [here](https://groups.google.com/forum/#!searchin/librosa/windows/librosa/Z1-HXBsHLi0/w-4QJIs4CwAJ)).

There shouldn't be any need for MSVC++, since librosa is all pure python.

**Comment by bmcfee** [comment]
Since librosa has no C/C++ code, I'm sure that this issue must be coming from a dependency.

However, I'll reopen this issue if someone can demonstrate that it's librosa's fault.
