### ISSUE TITLE
Fix chroma_stft docs for power spectrogram

### ISSUE THREAD

**Issue by bmcfee** [bmcfee/librosa#321]
The documentation specifies that spectrogram input should be power (not energy), but the example code uses energy spectrograms.

**Comment by dpwe** [comment]
You mean: ".. power (not amplitude), but the example code uses conventional
amplitude spectrograms."

I don't think there's a right answer here.  Typically when combining
different frequency bins, there's a bias towards combining in the power
domain, since that would be the actual observed total energy of a signal
containing (say) sines at 220 and 440 Hz.

However, I guess chroma bins are trying to model the total perceived
strength of semitones across different octaves.  I'm not aware of any
research on how pitch intensities in octave relations combine, but the
"critical band" stuff says that sound intensity spread over relatively wide
bands is perceived as louder than the same energy concentrated in a narrow
band.  So that would seem to favor adding linear intensity rather than
combining in the power domain.

So I think we should probably not specify the kind of spectrogram input
(power or amplitude), but stick with amplitude in the example code.

  DAn.

**Comment by bmcfee** [comment]
Agreed -- the issue here is just that the example doesn't match the rest of the docs, leading to confusion.  Maybe I'll just add a second example to illustrate the difference between amplitude- and power-based chroma calculation.


> So I think we should probably not specify the kind of spectrogram input
> (power or amplitude), but stick with amplitude in the example code.

I'd rather keep power in the example code, since it illustrates how to compute the same chromagram in two different ways: via `librosa.feature.chroma_stft(y)` or `librosa.feature.chroma_stft(S=np.abs(D)**2)`.
