### ISSUE TITLE
istft: reconstructed signal too short if len(signal)/hop_length is not an integer 

### ISSUE THREAD

**Issue by sebewert** [bmcfee/librosa#328]
Hi,

I am having issues using the reconstruction code in istft (librosa 0.4.2): reconstructed signal are too short. Here is some code illustrating the issue (I am using anaconda 4.0.0):

```python
from __future__ import ( division, absolute_import, print_function, unicode_literals )
import librosa
import numpy as np

n_fft = 4096
hop_length = np.round(n_fft/4)
y = np.random.rand(n_fft+hop_length-1)
Z = librosa.core.stft(y, n_fft=n_fft, hop_length=hop_length, center=True)
y_recon = librosa.core.istft(Z, hop_length=hop_length, center=True)

print(Z.shape)
print(len(y))
print(len(y_recon))
```
Output:
(2049, 5)
5119
4096
#####################################################################

Using y = np.random.rand(n_fft+hop_length) instead the output is
(2049, 6)
5120
5120

I looked a little bit into it. It does not seem to be stft as I think enough frames are computed in both cases (unless one is really concerned about numerical issues resulting from using non-rectangular windows - in that case it might be good to compute more frames in stft). However, it seems istft is not making use of all frames and hence the reconstructed signals are too short.

**Comment by bmcfee** [comment]
Before digging into this: do you see the same behavior if you say `center=False` in stft/istft?  (i.e., use left-aligned frames)

Otherwise, I'm not sure I have a good answer for you here.  ISTFT will only reconstruct whole frames, so given  the 5-column stft output in your first example, it's doing the "right" thing IMO.  Likewise for the 6-frame STFT in the second example.  There will always be some rounding effects when using full frames here.

Given that, I'd say that if anything is wrong here, it's that the initial STFT is too short.  The relevant bit of code is [here](https://github.com/bmcfee/librosa/blob/master/librosa/core/spectrum.py#L162-L167); the framing operation rounds down to get a whole number of frames because A) it's in-place reshaping, B) it would otherwise have to hallucinate data.

I think the best solution here is to explicitly pre-pad your signal (if that's what you want), and keep track of your target signal length.  Something like the following:

```python
>>> n = len(y)
>>> y_pad = np.pad(y, [0, np.mod(n, hop_length)], mode='constant')
>>> D = librosa.stft(y_pad, hop_length=hop_length)
>>> # Process D -> D_processed
>>> y_out = librosa.util.fix_length(librosa.istft(D_processed, hop_length=hop_length), n)
```
(note: code above is not tested, may need some corrections)

This way, you have explicit control over the length and padding of your signal, and no assumptions are made on librosa's end about how to handle the edge cases.

**Comment by sebewert** [comment]
Hi,

woah that was quick... Thanks!

And yes, the output length is the same for my two cases, setting center=False:
(2049, 1)
5119
4096

Your work around is how I do it right now. I thought that istft behaving like that would be the intended variant. However, if not, I can live with this work around...

BTW: since for center=false no windows are overlapping, the numerical issues related to no using rectangular windows are getting quite high, see following code snippet:
###################################################################
from __future__ import ( division, absolute_import, print_function, unicode_literals )
import librosa
import numpy as np

flagCenter = False
n_fft = 4096
hop_length = np.round(n_fft/4)
y = np.random.rand(n_fft+hop_length-1)
Z = librosa.core.stft(y, n_fft=n_fft, hop_length=hop_length, center=flagCenter)
y_recon = librosa.core.istft(Z, hop_length=hop_length, center=flagCenter)

print(Z.shape)
print(len(y))
print(len(y_recon))
print(np.max(np.abs(y[0:len(y_recon)]-y_recon)))
###################################################################
Output:
(2049, 1)
5119
4096
0.145359196379

With Center=True, the last value is only 1.81176516012e-07

**Comment by bmcfee** [comment]
> BTW: since for center=false no windows are overlapping,

The windows still overlap without centering, it's just that the first frame is centered at `n_fft//2` instead of `0` (and there is no padding of the signal).  As such, you lose a little at the beginning and end of the signal due to windowing tapering to 0.  If you use `window=np.ones` (in both stft and istft), then the max error stays down around 1e-7 with and without centering.

With a normal window (eg `hann`), if you replace the `max` error with `mean` it should be around 1e-5 ; median error should be around 1e-8 (with and without centering).

**Comment by sebewert** [comment]
Ah yes, I should have been more clear. I meant my specific case where Z.shape is (2049, 1) - in this specific case, no windows are overlapping (because there is only one) and here the boundary cases become strongest (as you had explained).

**Comment by bmcfee** [comment]
Ok, cool.  It sounds like everything is behaving correctly then, for appropriate definitions of "correctly".

Maybe to avoid future confusion, the documentation could be expanded or clarified?  Open to suggestions here.

**Comment by sebewert** [comment]
Yes.

Since reconstruction accuracy is quite important for source separation (as unfortunately essentially all current evaluation methods depend heavily on energy), maybe a comment on including the padding to get a precise reconstruction could help.

Currently, I am simply padding by n_fft/2 to get a behavior at the end similar to the start (the centered window at the start). This removes any numerical issues from window up/downscaling at the end and brings the reconstruction accuracy with unmodified signals close to the machine eps.

Thanks for the quick responses!

```python
y = np.concatenate( (y,np.zeros(n_fft/2)), axis=0)

**Comment by bmcfee** [comment]
> Since reconstruction accuracy is quite important for source separation (as unfortunately essentially all current evaluation methods depend heavily on energy), maybe a comment on including the padding to get a precise reconstruction could help.

Yeah, fair point.  Maybe just including (a working version of) the code snippet above for padding/trimming in the examples section would suffice?

> y = np.concatenate( (y,np.zeros(n_fft/2)), axis=0)

`np.pad` is a better way to do this; should save you at least one buffer allocation.

**Comment by sebewert** [comment]
> np.pad is a better way to do this; should save you at least one buffer allocation

Ah, thanks. Still kind of new to python...

**Comment by stefan-balke** [comment]
> Ah, thanks. Still kind of new to python...

Welcome to the show 👍
